### ISSUE TITLE
make db-prepare-artix7 fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by JamesTimothyMeech** [f4pga/prjxray#2146]
`(base) james@james-System-Product-Name:~/Desktop/Casino/prjxray$ make db-prepare-artix7`

`Preparing artix7 files`
`Traceback (most recent call last):
  File "/home/james/Desktop/Casino/prjxray/utils/create_environment.py", line 14, in <module>
    from prjxray.util import get_part_information, get_part_resources, get_fabric_for_part
ModuleNotFoundError: No module named 'prjxray'
Traceback (most recent call last):
  File "./utils/update_parts.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
make: *** [Makefile:190: db-prepare-artix7] Error 1`

**Comment by JamesTimothyMeech** [comment]
`(base) james@james-System-Product-Name:~/Desktop/Casino/prjxray$ make db-prepare-artix7

Preparing artix7 files
============================
Traceback (most recent call last):
  File "/home/james/Desktop/Casino/prjxray/utils/create_environment.py", line 14, in <module>
    from prjxray.util import get_part_information, get_part_resources, get_fabric_for_part
ModuleNotFoundError: No module named 'prjxray'
Traceback (most recent call last):
  File "./utils/update_parts.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
make: *** [Makefile:190: db-prepare-artix7] Error 1
`

**Comment by JamesTimothyMeech** [comment]
Also getting this error 
```(base) james@james-System-Product-Name:~/Desktop/Casino/prjxray$ make db-prepare-parts

Preparing artix7 files
============================
Traceback (most recent call last):
  File "/home/james/Desktop/Casino/prjxray/utils/create_environment.py", line 14, in <module>
    from prjxray.util import get_part_information, get_part_resources, get_fabric_for_part
ModuleNotFoundError: No module named 'prjxray'
Traceback (most recent call last):
  File "./utils/update_parts.py", line 15, in <module>
    from prjxray import util
ModuleNotFoundError: No module named 'prjxray'
make: *** [Makefile:190: db-prepare-artix7] Error 1


```

**Comment by JamesTimothyMeech** [comment]
This was a Python dependency problem specific to my machine
