### ISSUE TITLE
Spartan 7 New Part Support

### ISSUE THREAD

**Issue by kingdipdip** [f4pga/prjxray#2452]
Hello All!

I am running into issues with adding additional parts to the Spartan 7 Family. Specifically, I am trying to add support for the Spartan xc7s25. I am following the "Guide to adding a new device to an existing family" and am receiving an error when sourcing the new settings file. I am using the baseline "spartan7.sh" to copy setting from and altering XRAY_PART="xc7s50fgga484-1" to XRAY_PART="xc7s25csga324-1" and changing the bounds accordingly. I believe there must be some exception to guide for spartan7, since it is not well supported. I have proceeded with the device.yaml adjustments too. 

# device to fabric mapping
"xc7s50":
  fabric: "xc7s50"
"xc7s25":
  fabric: "xc7s25"

source settings/spartan7_25.sh
Traceback (most recent call last):
  File "/home/kingd/Downloads/prjxray/utils/create_environment.py", line 66, in <module>
    main()
  File "/home/kingd/Downloads/prjxray/utils/create_environment.py", line 59, in main
    environment = get_environment_variables()
  File "/home/kingd/Downloads/prjxray/utils/create_environment.py", line 37, in get_environment_variables
    part_info = get_part_information(db_root, part)
  File "/home/kingd/Downloads/prjxray/prjxray/util.py", line 93, in get_part_information
    assert part, "Part {} not found in {}".format(part, part_mapping)
AssertionError: Part None not found in {'xc7s50csga324-1': {'device': 'xc7s50', 'package': 'csga324', 'speedgrade': '1'}, 'xc7s50csga324-1IL': {'device': 'xc7s50', 'package': 'csga324', 'speedgrade': '1IL'}, 'xc7s50csga324-2': {'device': 'xc7s50', 'package': 'csga324', 'speedgrade': '2'}, 'xc7s50fgga484-1': {'device': 'xc7s50', 'package': 'fgga484', 'speedgrade': '1'}, 'xc7s50fgga484-1IL': {'device': 'xc7s50', 'package': 'fgga484', 'speedgrade': '1IL'}, 'xc7s50fgga484-2': {'device': 'xc7s50', 'package': 'fgga484', 'speedgrade': '2'}, 'xc7s50ftgb196-1': {'device': 'xc7s50', 'package': 'ftgb196', 'speedgrade': '1'}, 'xc7s50ftgb196-1IL': {'device': 'xc7s50', 'package': 'ftgb196', 'speedgrade': '1IL'}, 'xc7s50ftgb196-2': {'device': 'xc7s50', 'package': 'ftgb196', 'speedgrade': '2'}}

After running source, 
make db-prepare-spartan7

Preparing spartan7 files
============================
Find pins for xc7s50csga324-1
Find pins for xc7s50fgga484-1
Find pins for xc7s50ftgb196-1

Here you can see that the new device is not found. Any assistance with this would be greatly appreciated! I have been troubleshooting this for who knows how long and have not found a solution. 

Thanks!

**Comment by huangwenlin222** [comment]
I got the same problem. It might be because Vivado 2017.2 doesn't support xc7s25 devices. That is my thought. #2555
